version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_BANNER_URL=${EMAIL_BANNER_URL}
      - EMAIL_FROM=${EMAIL_FROM}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAILER_DELIVERY_METHOD=${MAILER_DELIVERY_METHOD}
      - APP_BASE_URL=${APP_BASE_URL}
      - ACTIVATION_FAILURE_URL=${ACTIVATION_FAILURE_URL}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - ACCESS_TOKEN_TTL_SECONDS=${ACCESS_TOKEN_TTL_SECONDS}
      - REFRESH_TOKEN_TTL_SECONDS=${REFRESH_TOKEN_TTL_SECONDS}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "bundle exec rails db:create db:migrate && rails db:seed && bundle exec rails s -b 0.0.0.0 -p 3000"
    restart: unless-stopped

  resque:
    build: .
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_BANNER_URL=${EMAIL_BANNER_URL}
      - EMAIL_FROM=${EMAIL_FROM}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAILER_DELIVERY_METHOD=${MAILER_DELIVERY_METHOD}
      - APP_BASE_URL=${APP_BASE_URL}
      - ACTIVATION_FAILURE_URL=${ACTIVATION_FAILURE_URL}
    depends_on:
      - db
      - redis
    command: bundle exec rake resque:work QUEUE='*'
    restart: unless-stopped

  resque-scheduler:
    build: .
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_BANNER_URL=${EMAIL_BANNER_URL}
      - EMAIL_FROM=${EMAIL_FROM}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAILER_DELIVERY_METHOD=${MAILER_DELIVERY_METHOD}
      - APP_BASE_URL=${APP_BASE_URL}
      - ACTIVATION_FAILURE_URL=${ACTIVATION_FAILURE_URL}
    depends_on:
      - db
      - redis
    command: bundle exec rake resque:scheduler
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data: